config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get "/console_it", to: "home#console_it"
  get "/links", to: "home#links"
  
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def console_it
  end

  def links
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    render :edit_form
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = "User updated :D"
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong D:"
      render :edit_form
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :photo, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/console_it.html.erb
<%= console %>
<section class="section">
  <div class="container">
    Salu2, esta consola tiene mas poder del que puedes imaginar, asi que procura no jugar
    demasiado con ella. Está aquí para apoyarte por si tuviste problemas al instalar ruby.
    Por favor, no hagas daño a los demás y toma mucha agua :)
  </div>
</section>

app/views/home/index.html.erb
<section class="section">
  <div class="container">

    <div class="cards-container">
      <% @users.each do |user| %>
          <div class="card">
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <% if user.photo.present? %>
                      <%= image_tag user.photo %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4"> <%= user.name ||"Noname"  %> </p>
                  <p class="subtitle is-6"> <%= user.email %> </p>
                </div>
              </div>

              <div class="content">
                <%= user.description %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

  </div>
</section>

app/views/home/links.html.erb
<section class="section">
  <div class="container">
    <h2 class="title"> Cosas monas </h2> 

    <div class="list">
      <%= link_to "Planning", "https://docs.google.com/document/d/1PSu5OFBULiY5LL-oS8kGuysOqgCnHzjXtX26QJfoSZ8/edit?usp=sharing", class: "list-item" %>
      <%= link_to "Session 1 Introduction to Ruby", "https://docs.google.com/presentation/d/1RrztwY1EFompckh6p5XQECq4z2EUYCF_-K3IwHEM0rc/edit?usp=sharing", class: "list-item" %>
      <%= link_to "Session 2 Ruby Fundamentals", "https://docs.google.com/presentation/d/1Tczr910RUwkgLQpyDCO5s79R92A912A3mUkIC878Qc4/edit?usp=sharing", class: "list-item" %>
      <%= link_to "Session 3 OOP on Ruby", "https://docs.google.com/presentation/d/1h7QRClV5CP7pNK918Kt8ybenGp0AA2otZViqj7mzNNM/edit?usp=sharing", class: "list-item" %>
    </div>

    El día de hoy, Viernes 4 de Octubre no podré asistir por cuestiones laborales a impartir el curso :sad:
    Sin embargo, para poderles acreditar la clase de hoy, requeriré que me muestren avances de la página, y los evaluaré con lo siguiente:
    <ul>
      <li> -  Añadir funciones de <b> Edit </b>, <b> Update </b> y <b> Delete </b> </li>
      <li> -  Añadir CSS para estilizar las vistas. Pueden usar cualquier framework de CSS: Bootstrap, Materialize, Bulma (recomendación personal uwu), etc </li>
    </ul>
    <br>
    Puede ser en equipos de hasta 4 changos, de preferencia 2 o 3 para que todos puedan moverle al código y practicar. Sin embargo, dado que pocos lograron instalar exitosamente Ruby on Rails,
    se permitirán los 4.

    Les dejo por aquí algo de Bibliografía para que se puedan basar en ella:
    <ul>
      <li> -  <a href="https://github.com/jbrizuela2/Fasbok"> Repositorio de lo que se hizo la clase anterior </a> </li>
      <li> -  <a href="https://guides.rubyonrails.org/action_controller_overview.html"> Action Controller </a> </li>
      <li> -  <a href="https://guides.rubyonrails.org/active_record_basics.html"> Active Record </a> </li>
      <li> -  <a href="https://medium.com/@nancydo7/ruby-on-rails-crud-tutorial-899117710c7a"> Un tutorial que encontré por allí xd </a> </li>
      <li> -  <a href="https://bulma.io/"> Documentación de Bulma.io  </a> </li>
      <li> -  <a href="https://getbootstrap.com/"> Documentación de Bootstrap  </a> </li>
    </ul>
    <br> 
    Cualquier otra duda, pueden enviarme mensaje a <a href="mailto:juan.brizuela@michelada.io"> juan.brizuela@michelada.io </a> <br>

    P.D: En un rato más les subiré una presentación de lo que hemos visto hasta ahora (o quizá no :'v), para que los que no han asistido puedan ponerse al corriente uwu  <br>
    P.D2: Buen fin de Semana :D
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/messages" if flash.any? %>
    <%= yield %>
  </body>
</html>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='notification is-<%= name == "notice" ? "success" : name == "alert" ? danger : name %>'>
    <button class="delete"></button>
    <p class="has-text-white is-size-5 has-text-weight-medium">
      <%= msg %>
    </p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%# <%=  link_to "Console", console_it_path, class: "navbar-item" %>
      <%= link_to "Links", links_path, class: "navbar-item" %>
    </div>
    
    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to current_user.name.blank? ? current_user.email : current_user.name, edit_user_path(current_user), class: "label"%>
        <% end %>
      </div>

      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "button is-primary is-primary" %>
          <% else%>
            <%= link_to "Sign up", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/edit_form.html.erb
<section class="section">
  <div class="container">
    <%= form_for(current_user) do |f| %>
      <div class="field">
        <%= f.label :name, class: "label" %>
        <div class="control">
          <%= f.text_field :name, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= f.label :email, class: "label" %>
        <div class="control">
          <%= f.text_field :email, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= f.label "Photo url", class: "label" %>
        <div class="control">
          <%= f.text_field :photo, class: "input" %>
        </div>
      </div>   

      <div class="field">
        <%= f.label "Bio", class: "label" %>
        <div class="control">
          <%= f.text_area :description, class: "textarea" %>
        </div>
      </div>   

      <div class="field">
        <div class="control">
          <%= f.submit "Guardar", class: "button is-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</section>